//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactoryContentRootAttribute("EmployeeTaskAPI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null", "C:\\Users\\v-kailhu\\source\\repos\\newEmployeeTask\\EmployeeTaskAPI", "EmployeeTaskAPI.csproj", "0")]
[assembly: System.Reflection.AssemblyCompanyAttribute("EmployeeTaskAPIIntegrationTest")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("EmployeeTaskAPIIntegrationTest")]
[assembly: System.Reflection.AssemblyTitleAttribute("EmployeeTaskAPIIntegrationTest")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

